name: ML Model CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: student_performance_env
          environment-file: MLProject/conda.yaml
          python-version: 3.9
          auto-activate-base: false
          use-mamba: true

      - name: Verifikasi Environment
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Jalankan MLflow Project
        shell: bash -l {0}
        run: |
          cd MLProject
          RUN_ID_PATH="$PWD/ci_run_id.txt"
          mlflow run . -P data_path=siswa_clean.csv -P model_path=model_ci.joblib -P run_id_path=$RUN_ID_PATH

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model_ci
          path: MLProject/model_ci.joblib

      - name: Baca Run ID dari file
        run: |
          RUN_ID=$(cat MLProject/ci_run_id.txt)
          echo "RUN_ID=$RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image via MLflow
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/model" -n "lopingsuee/student-performance-ci:latest"

      - name: Push Docker image
        run: |
          docker push "lopingsuee/student-performance-ci:latest"
